### ISSUE TITLE
Files in nar serialisation are not sorted.

### ISSUE THREAD

**Issue by Mic92** [nix-community/go-nix#106]
While the c++ implementation inserts the file names into a sorted map, the go implementation just emits them as returned by the os:

https://github.com/nix-community/go-nix/blob/1f9567c0a1e5fa52ca0401bf1241d1ec7643c097/pkg/nar/dump.go#L105

This would likely break if the filesystem returns file in a different order than how the std::map is sorted.

**Comment by flokli** [comment]
No, `files` is coming from the `os.ReadDir` call above:

https://github.com/nix-community/go-nix/blob/1f9567c0a1e5fa52ca0401bf1241d1ec7643c097/pkg/nar/dump.go#L99

Entries from `os.ReadDir` are sorted by filename:

```
❯ go doc os.ReadDir
package os // import "os"

func ReadDir(name string) ([]DirEntry, error)
    ReadDir reads the named directory, returning all its directory entries
    sorted by filename. If an error occurs reading the directory, ReadDir
    returns the entries it was able to read before the error, along with the
    error.
```
